[workspace]
members = [
    "sweat",
    "sweat",
    "sweat-integration",
    "integration-tests",
    "defer-stub"
]

resolver = "2"

[workspace.dependencies]
tokio = "1.28.0"
anyhow = "1.0.75"
async-trait = "0.1.74"

near-sdk = "4.1.1"
near-contract-standards = "4.1.1"

near-units = "0.2.0"
near-workspaces = "0.9.0"

sweat-model = { path = "model" }
sweat-integration = { path = "sweat-integration" }

integration-trait = { git = "https://github.com/sweatco/integration-utils.git", rev = "d5dac489cad973b5c111015a16ec64afaf288c6b" }
integration-utils = { git = "https://github.com/sweatco/integration-utils.git", rev = "d5dac489cad973b5c111015a16ec64afaf288c6b" }
