[package]
name = "sweat"
version = "0.1.0"
authors = []
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
static_assertions = "1.1.0"
near-sdk = {git = "https://github.com/sweatco/near-sdk-rs", rev = "c581e8cd8dd5264eafb8a139b4a465008e61e1d8"}
near-contract-standards = {git = "https://github.com/sweatco/near-sdk-rs", rev = "c581e8cd8dd5264eafb8a139b4a465008e61e1d8"}
