[package]
name = "sweat"
version = "0.1.0"
authors = []
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
static_assertions = "1.1.0"
near-sdk = { git = "https://github.com/sweatco/near-sdk-rs", rev = "3cce3a38eba94ee13653cf2de46d1c667b320d38" }
near-contract-standards = { git = "https://github.com/sweatco/near-sdk-rs", rev = "3cce3a38eba94ee13653cf2de46d1c667b320d38" }
